algo_trading/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    # Instrument
    path("instruments/show/<int:pk>", views.instrument_by_pk, name="instrument"),
    path(
        "instruments/show/<str:symbol>",
        views.instrument_by_symbol,
        name="instrument-symbol",
    ),
    path("instruments/add", views.add_instruments, name="add-instrument"),
    path("instruments", views.list_instruments, name="list-instruments"),
    # Zerodha
    path("zerodha_login_url", views.zerodha_login_url, name="zerodha-login-url"),
    path("zerodha_req_token", views.zerodha_req_token, name="zerodha-req-token"),
    path("zerodha_instruments", views.zerodha_instruments),
    # Trading System
    path(
        "trading_system/place_options_call",
        views.place_options_call,
        name="place-options-call",
    ),
    path("trading_system/calls/<int:pk>", views.trading_signal, name="trading-signal"),
    path("trading_system/calls/options", views.options_calls, name="options-calls"),
]

# Additional URLs from other apps
urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

algo_trading/models/instruments.py
from django.db import models
from django.db.models import Q
from django.urls import reverse

from .managers.instrument_manager import InstrumentManager


class Instrument(models.Model):
    symbol = models.CharField(max_length=30, db_index=True, unique=True)

    class InstrumentType(models.TextChoices):
        EQUITY = "EQ", "Equity"
        FUTURES = "FUT", "Futures"
        CALL_OPTION = "CE", "Call Option"
        PUT_OPTION = "PE", "Put Option"
        INDEX = "IX", "Index"
        CURRENCY = "CU", "Currency"
        CURRENCY_FUTURES = "CF", "Currency Futures"
        CURRENCY_OPTIONS = "CO", "Currency Options"
        INDEX_FUTURES = "IF", "Index Futures"
        INDEX_OPTIONS = "IO", "Index Options"

    instrument_type = models.CharField(
        max_length=3,
        choices=InstrumentType.choices,
        default=InstrumentType.EQUITY,
    )

    # fields to store Zerodha-specific info.
    instrument_token = models.IntegerField("zerodha instrument token", default=0)
    exchange_token = models.CharField(
        "zerodha exchange token", max_length=100, default=""
    )
    trading_symbol = models.CharField(
        "zerodha trading symbol", max_length=100, default=""
    )
    name = models.CharField(
        "zerodha company name", default=None, null=True, blank=True, max_length=100
    )
    expiry = models.CharField(
        "zerodha expiry date", default=None, null=True, blank=True, max_length=100
    )
    strike = models.DecimalField(
        "zerodha strike price",
        default=None,
        null=True,
        blank=True,
        max_digits=15,
        decimal_places=5,
    )
    tick_size = models.DecimalField(
        "zerodha tick size",
        default=None,
        null=True,
        blank=True,
        max_digits=15,
        decimal_places=5,
    )
    lot_size = models.IntegerField(
        "zerodha lot size", default=None, null=True, blank=True
    )
    segment = models.CharField("zerodha segment", max_length=50, default="")
    exchange = models.CharField("zerdoha exchange", max_length=50, default="")

    class Meta:
        verbose_name = "Instrument"
        verbose_name_plural = "Instruments"

        indexes = [
            models.Index(fields=["symbol"], name="instrument_symbol_idx"),
            models.Index(
                fields=["instrument_type"], name="instrument_instrument_type_idx"
            ),
            models.Index(
                fields=["trading_symbol", "exchange"], name="instrument_identifier_idx"
            ),
        ]

        constraints = [
            models.UniqueConstraint(
                fields=["trading_symbol", "exchange"],
                name="unique_instrument_identifier",
                condition=~Q(trading_symbol="") & ~Q(exchange=""),
                violation_error_message="Instrument name at exchange already exists",
            )
        ]

        get_latest_by = "id"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("instrument-symbol", args=[self.trading_symbol])

    # TODO: Define custom methods here
    objects = InstrumentManager()

algo_trading/models/ohlc_data_daily.py
from django.db import models

from .instruments import Instrument


class OhlcDataDaily(models.Model):
    # REFACTOR: Create a custom field for `DecimalField` for capturing all
    # price fields from Trading API

    # Deliberately calling the timestamp column by a simplified name `date`
    # as most trading APIs have date as the indicating column
    date = models.DateTimeField("trade time")
    open = models.DecimalField("open price", max_digits=15, decimal_places=5)
    high = models.DecimalField("high price", max_digits=15, decimal_places=5)
    low = models.DecimalField("low price", max_digits=15, decimal_places=5)
    close = models.DecimalField("close price", max_digits=15, decimal_places=5)

    # Set default for now, until we get this from zerodha APIs
    last_price = models.DecimalField(
        "last price", max_digits=15, decimal_places=5, default=0.0
    )

    # Refers to the instrument to which this daily data set belongs to.
    # Renames the related_name on `instrument` as `daily_data`,
    # yielding following methods:
    # ```
    # instrument.daily_data.count(), instrument.daily_data.filter()
    # instrument.daily_data.add()
    # instrument.daily_data.create()
    # instrument.daily_data.remove()
    # instrument.daily_data.clear()
    # instrument.daily_data.set()
    # ```
    instrument = models.ForeignKey(
        Instrument,
        on_delete=models.CASCADE,
        related_name="daily_data",
    )

    class Meta:
        verbose_name = "OhlcDataDaily"
        verbose_name_plural = "OhlcDataDailies"

        indexes = [
            models.Index(fields=["date"], name="ohlcv_daily_date_idx"),
            models.Index(
                fields=["instrument", "date"], name="ohlcv_dly_instrument_date_idx"
            ),
        ]

        constraints = [
            # Each day/date-time will have many entries for different instruments,
            # but for each instrument the day/date-time should be unique and
            # referring to the _source of truth_ for that timestamp.
            models.UniqueConstraint(
                fields=["instrument", "date"],
                name="unique_instrument_ohlcv_data_daily_date",
                violation_error_message="Date for instrument already exists, must be unique",  # noqa
            )
        ]

        get_latest_by = "date"  # should it be -date?, check when we have data

    def __str__(self):
        return str(self.date)

    # TODO: Define custom methods here

    @property
    def date_in_tables(self) -> str:
        """Return date in Month Day, Year format for display in tables

        Parameters
        ----------
        self:
            The object instance

        Returns
        -------
        str
            Date in April 01, 1990 format
        """
        return self.date.strftime("%B %d, %Y")

algo_trading/models/ohlcv_data_daily.py
from django.db import models
from .instruments import Instrument


class OhlcvDataDaily(models.Model):
    # REFACTOR: Create a custom field for `DecimalField`for capturing all price fields from Trading API

    # Deliberately calling the timestamp column by a simplified name `date` as most trading APIs have
    # date as the indicating column
    date = models.DateTimeField("trade time")
    open = models.DecimalField("open price", max_digits=15, decimal_places=5)
    high = models.DecimalField("high price", max_digits=15, decimal_places=5)
    low = models.DecimalField("low price", max_digits=15, decimal_places=5)
    close = models.DecimalField("close price", max_digits=15, decimal_places=5)

    # Set default for now, until we get this from zerodha APIs
    last_price = models.DecimalField("last price", max_digits=15, decimal_places=5, default=0.0)

    # Refers to the instrument to which this daily data set belongs to.
    # Renames the related_name on `instrument` as `daily_data`, resulting in the following methods:
    # ```
    # instrument.daily_data.count(), instrument.daily_data.filter()
    # instrument.daily_data.add()
    # instrument.daily_data.create()
    # instrument.daily_data.remove()
    # instrument.daily_data.clear()
    # instrument.daily_data.set()
    # ```
    instrument = models.ForeignKey(
        Instrument,
        on_delete=models.CASCADE,
        related_name="daily_data",
    )

    class Meta:
        verbose_name = "OhlcvDataDaily"
        verbose_name_plural = "OhlcvDataDailies"

        indexes = [
            models.Index(fields=['date'], name="ohlcv_daily_date_idx"),
            models.Index(fields=['instrument', 'date'], name="ohlcv_dly_instrument_date_idx"),
        ]

        constraints = [
            # Each day/date-time will have many entries for different instruments, but for each
            # instrument the day/date-time should be unique and referring to the _source of truth_
            # for that timestamp.
            models.UniqueConstraint(
                fields=['instrument', 'date'],
                name="unique_instrument_ohlcv_data_daily_date",
                violation_error_message="Date for instrument already exists, must be unique",
            )
        ]

        get_latest_by = "date"  # should it be -date?, check when we have data

        # THIS IS NOT WORKING, CHECK AGAIN
        # Adds `instrument.get_ohlcv_data_daily_order(), instrument.set_ohlcv_data_daily_order()`
        # to Instrument class' instances.
        # Adds `ohlcv_data_daily.get_next_in_order(), ohlcv_data_daily.get_previous_in_order()` to
        # this class' instances.
        # This implicitly sets the `ordering` field.
        #
        # WARN: DON'T USE ORDERING AGAIN IN THIS MODEL
        # order_with_respect_to = "instrument_id"

    def __str__(self):
        return str(self.date)

    def get_absolute_url(self):
        return ('')

    # TODO: Define custom methods here

algo_trading/views/instruments_view.py
# Create your views here.
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_http_methods

from ..forms.instruments.add_instrument_form import AddInstrumentForm
from ..models.instruments import Instrument


@require_http_methods(["GET"])
def instrument_by_pk(request, pk: int):
    """Show an `Instrument` instance identified by its primary key: `pk`"""

    instrument = get_object_or_404(Instrument, pk=pk)
    return display_instrument(request, instrument)


@require_http_methods(["GET"])
def instrument_by_symbol(request, symbol: str):
    """Show an `Instrument` instance identified by its `symbol`"""

    instrument = Instrument.objects.get_by_symbol(symbol)
    return display_instrument(request, instrument)


def display_instrument(request, instrument: Instrument):
    """Common function to show an `Instrument`"""

    return render(
        request,
        "instruments/show.html",
        {
            "instrument": instrument,
            "daily_data": instrument.daily_data.order_by("-date"),
        },
    )


@require_http_methods(["GET", "POST"])
def add_instruments(request):
    """Add one or more instruments into the system

    Tries to create a new instrument from the form data.

    Internal function for the view, not to be called from outside.
    Processes the symbol through the yfinance API to collect basic info about the stock
    and creates a new Instrument instance from that info
    For the newly created Instrument, downloads all historical data till date and creates
    a record of type `OhlcvDataDaily` for every available date in the historical data with their
    OHLC entries.

    Parameters
    ----------
    request:
        The request object

    Raises
    ------
    Does not raise any error, but shows all failing symbols on the resulting page table
    Also shows the successfully imported symbols on the resulting page table
    """

    symbols_import_summary = {}
    if request.method == "POST":
        form = AddInstrumentForm(request.POST)

        if form.is_valid():
            symbols = [s.strip() for s in form.cleaned_data["symbol"].split(",")]
            symbols_import_summary = Instrument.objects.import_symbols_from_yf(symbols)

    else:
        form = AddInstrumentForm()

    return render(
        request,
        "instruments/add_instrument.html",
        {"form": form, "symbols_import_summary": symbols_import_summary},
    )


@require_http_methods(["GET"])
def list_instruments(request):
    """Show all instruments

    Shows all the instruments in the system. Currently only shows the last 100
    until pagination is being built into the frontend display system
    """

    instruments = Instrument.objects.filter()[:100]

    return render(
        request,
        "instruments/list_instruments.html",
        {
            "instruments": instruments,
        },
    )

algo_trading/views/trading_system_view.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_http_methods

from ..forms.zerodha.options_call_form import OptionsCallForm
from ..models.business_domain.trading_system import TradingSystem
from ..models.trading_signal import TradingSignal


@require_http_methods(["GET", "POST"])
def place_options_call(request):
    """Creates an option call via a TradingSignal object

    The POST request has the details of the call as received.
    Parses that to create a signal and places an order.
    Alerts the user if the same call was placed more than once
    Raises an error if the instrument is not found in the DB.

    Raises
    ------
    Error404 if the requested instrument does not exist in the list of instruments
    to trade from the daily zerodha import.

    Redirects to
    ------------
    Created trading Signal page, which will also have the order object.
    """

    # @TODO
    # check if duplicate call is placed with the same params accidentally.

    ts = TradingSystem()
    trading_signal = None

    if request.method == "POST":
        options_call_form = OptionsCallForm(request.POST)

        if options_call_form.is_valid():
            (trading_signal, order) = ts.place_order_from_call_blob(
                options_call_form.cleaned_data["call_blob"]
            )
            return redirect(trading_signal)
    else:
        options_call_form = OptionsCallForm()

    return render(
        request,
        "trading_system/place_options_call.html",
        {
            "form": options_call_form,
            "signal": trading_signal,
        },
    )


@require_http_methods(["GET"])
def trading_signal(request, pk: int):
    """Show a trading signal"""

    trading_signal = get_object_or_404(TradingSignal, pk=pk)

    return render(
        request,
        "trading_system/trading_signal.html",
        {"trading_signal": trading_signal},
    )


@require_http_methods(["GET"])
def options_calls(request):
    """Show all options calls"""

    options_calls = TradingSignal.objects.get_options_calls()

    return render(
        request,
        "trading_system/options_calls.html",
        {"options_calls": options_calls},
    )

algo_trading/views/zerodha_view.py
from django.http import JsonResponse
from django.shortcuts import redirect
from django.utils.http import urlencode
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.decorators.http import require_http_methods

from ..models.business_domain.kite_broker import KiteBroker


@require_http_methods(["GET"])
def zerodha_login_url(request):
    """Returns the login url for the zerodha client"""

    kite = KiteBroker()
    redirect_string = "&redirect_params=" + urlencode(
        {"redirect_to": request.GET.get("next")}
    )
    return JsonResponse({"zerodha_login_url": kite.login_url() + redirect_string})


@ensure_csrf_cookie
@require_http_methods(["GET"])
def zerodha_req_token(request):
    """Endpoint for receiving the successful login from Zerodha

    When a successful login and authorization with the Zerodha client happens from the
    UI, this endpoint is called by the zerodha app with the request token as a query
    parameter and an additional param called `redirect_to` which is sent by us with
    the login request to indicate which page this login was called from.

    Creates a session with the request token, receiving an access token from Zerodha
    in the process, and setting that in the kite broker client to facilitate
    further api calls. Also sets the refresh token for future uses. Unused for now.

    Redirects the user back to the page from where the login button on the UI
    was clicked.
    """
    zerodha_request_token = request.GET.get("request_token")
    # todo add handler if token is nil or status/success is false
    kite = KiteBroker()

    data = kite.create_session(zerodha_request_token)
    kite.set_access_token(data["access_token"])
    kite.set_refresh_token(data["refresh_token"])

    return redirect(request.GET.get("redirect_to"))


def zerodha_instruments(request):
    """View action for loading all instruments from Zerodha

    Provided as a convenience/testing method to see if the import from
    Zerodha is working correctly and importing the updated instrument list, if any.

    Returns a `JsonResponse` with the count of instruments imported per exchange
    """
    kite = KiteBroker()

    count_by_exchange = kite.load_instruments_for_today()

    return JsonResponse(count_by_exchange, safe=False)

algo_trading/templates/instruments/add_instrument.html
{% extends "base.html" %}

{% load django_bootstrap5 %}

{% block content %}
  <form action={% url "add-instrument" %} method="POST">
    {% csrf_token %}
    <h3>Enter one or more symbols that you wan't to import</h3>

    <label for="{{ form.symbol.id_for_label }}" class="form-label">{{ form.symbol.label }}</label>

    <div class="input-group input-group-lg mb-5">
        <span class="input-group-text svg-icon svg-icon-2x svg-icon-danger" id="basic-addon1">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M12.0444 17.9444V12.1444L17.0444 15.0444C18.6444 15.9444 19.1445 18.0444 18.2445 19.6444C17.3445 21.2444 15.2445 21.7444 13.6445 20.8444C12.6445 20.2444 12.0444 19.1444 12.0444 17.9444ZM7.04445 15.0444L12.0444 12.1444L7.04445 9.24445C5.44445 8.34445 3.44444 8.84445 2.44444 10.4444C1.54444 12.0444 2.04445 14.0444 3.64445 15.0444C4.74445 15.6444 6.04445 15.6444 7.04445 15.0444ZM12.0444 6.34444V12.1444L17.0444 9.24445C18.6444 8.34445 19.1445 6.24444 18.2445 4.64444C17.3445 3.04444 15.2445 2.54445 13.6445 3.44445C12.6445 4.04445 12.0444 5.14444 12.0444 6.34444Z" fill="currentColor"/>
          <path opacity="0.3" d="M7.04443 9.24445C6.04443 8.64445 5.34442 7.54444 5.34442 6.34444C5.34442 4.54444 6.84444 3.04443 8.64444 3.04443C10.4444 3.04443 11.9444 4.54444 11.9444 6.34444V12.1444L7.04443 9.24445ZM17.0444 15.0444C18.0444 15.6444 19.3444 15.6444 20.3444 15.0444C21.9444 14.1444 22.4444 12.0444 21.5444 10.4444C20.6444 8.84444 18.5444 8.34445 16.9444 9.24445L11.9444 12.1444L17.0444 15.0444ZM7.04443 15.0444C6.04443 15.6444 5.34442 16.7444 5.34442 17.9444C5.34442 19.7444 6.84444 21.2444 8.64444 21.2444C10.4444 21.2444 11.9444 19.7444 11.9444 17.9444V12.1444L7.04443 15.0444Z" fill="currentColor"/>
          </svg>
        </span>
        <input
          type="text"
          name="{{ form.symbol.html_name }}"
          class="form-control"
          id="{{ form.symbol.id_for_label }}"
          aria-describedby="basic-addon1"
          placeholder="Comma separated symbols for import"
          required
        />
    </div>
    <button class="btn btn-primary btn-hover-scale me-5">
      <span class="svg-icon svg-icon-2x">
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path opacity="0.3" d="M4.05424 15.1982C8.34524 7.76818 13.5782 3.26318 20.9282 2.01418C21.0729 1.98837 21.2216 1.99789 21.3618 2.04193C21.502 2.08597 21.6294 2.16323 21.7333 2.26712C21.8372 2.37101 21.9144 2.49846 21.9585 2.63863C22.0025 2.7788 22.012 2.92754 21.9862 3.07218C20.7372 10.4222 16.2322 15.6552 8.80224 19.9462L4.05424 15.1982ZM3.81924 17.3372L2.63324 20.4482C2.58427 20.5765 2.5735 20.7163 2.6022 20.8507C2.63091 20.9851 2.69788 21.1082 2.79503 21.2054C2.89218 21.3025 3.01536 21.3695 3.14972 21.3982C3.28408 21.4269 3.42387 21.4161 3.55224 21.3672L6.66524 20.1802L3.81924 17.3372ZM16.5002 5.99818C16.2036 5.99818 15.9136 6.08615 15.6669 6.25097C15.4202 6.41579 15.228 6.65006 15.1144 6.92415C15.0009 7.19824 14.9712 7.49984 15.0291 7.79081C15.0869 8.08178 15.2298 8.34906 15.4396 8.55884C15.6494 8.76862 15.9166 8.91148 16.2076 8.96935C16.4986 9.02723 16.8002 8.99753 17.0743 8.884C17.3484 8.77046 17.5826 8.5782 17.7474 8.33153C17.9123 8.08486 18.0002 7.79485 18.0002 7.49818C18.0002 7.10035 17.8422 6.71882 17.5609 6.43752C17.2796 6.15621 16.8981 5.99818 16.5002 5.99818Z" fill="currentColor"/>
        <path d="M4.05423 15.1982L2.24723 13.3912C2.15505 13.299 2.08547 13.1867 2.04395 13.0632C2.00243 12.9396 1.9901 12.8081 2.00793 12.679C2.02575 12.5498 2.07325 12.4266 2.14669 12.3189C2.22013 12.2112 2.31752 12.1219 2.43123 12.0582L9.15323 8.28918C7.17353 10.3717 5.4607 12.6926 4.05423 15.1982ZM8.80023 19.9442L10.6072 21.7512C10.6994 21.8434 10.8117 21.9129 10.9352 21.9545C11.0588 21.996 11.1903 22.0083 11.3195 21.9905C11.4486 21.9727 11.5718 21.9252 11.6795 21.8517C11.7872 21.7783 11.8765 21.6809 11.9402 21.5672L15.7092 14.8442C13.6269 16.8245 11.3061 18.5377 8.80023 19.9442ZM7.04023 18.1832L12.5832 12.6402C12.7381 12.4759 12.8228 12.2577 12.8195 12.032C12.8161 11.8063 12.725 11.5907 12.5653 11.4311C12.4057 11.2714 12.1901 11.1803 11.9644 11.1769C11.7387 11.1736 11.5205 11.2583 11.3562 11.4132L5.81323 16.9562L7.04023 18.1832Z" fill="currentColor"/>
        </svg>
      </span>
      Fetch &amp; Validate Symbols
    </button>
  </form>

  {% if symbols_import_summary|length > 0 %}
    {% if symbols_import_summary.failed|length > 0 %}
      <div>
        <p class="header">List of symbols that failed to import</p>
          <table class="failed-symbols table rounded table-striped border gy-7 gs-7">
            <thead>
              <tr>
                <th>#</th>
                <th>Symbol</th>
                <th>Failure reason</th>
              </tr>
            </thead>

            <tbody>
              {% for failed_sym in symbols_import_summary.failed %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ failed_sym.symbol }}</td>
                  <td>{{ failed_sym.reason }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
      </div>
    {% endif %}

    {% if symbols_import_summary.created|length > 0 %}
      <div>
        <p class="header">Successfully imported symbols</p>
        {% include "instruments/display_meta_in_table.html" with instruments=symbols_import_summary.created %}
    </div>
    {% endif %}
  {% endif %}
{% endblock %}

algo_trading/templates/instruments/display_meta_in_table.html
{% load static %}

<div class="table-responsive">
  <table class="instruments-list table gy-5 gs-5 align-middle">
    <thead>
      <tr class="fw-bold text-muted bg-light">
        <th class="ps-4 rounded-start min-w-25px">#</th>
        <th>Symbol</th>
        <th>Name</th>
        <th>Exchange</th>
        <th>Instrument Type</th>
        <th>Segment</th>
        <th>Expiry</th>
        <th>Lot Size</th>
        <th>Tick Size</th>
        <th>Strike</th>
        <th>Exchange Token</th>
        <th class="text-end rounded-end">Instrument Token</th>
      </tr>
    </thead>

    <tbody>
      {% for instrument in instruments %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>
            <a href={% url "instrument-symbol" instrument.symbol %}>
              {{ instrument.trading_symbol }}
            </a>
          </td>
          <td>{{ instrument.name }}</td>
          <td>{{ instrument.exchange }}</td>
          <td>{{ instrument.instrument_type }}</td>
          <td>{{ instrument.segment }}</td>
          <td>{{ instrument.expiry }}</td>
          <td>{{ instrument.lot_size }}</td>
          <td>{{ instrument.tick_size }}</td>
          <td>{{ instrument.strike }}</td>
          <td>{{ instrument.exchange_token }}</td>
          <td class="text-end">{{ instrument.instrument_token }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<link href="{% static 'plugins/custom/datatables/datatables.bundle.css' %}" rel="stylesheet" type="text/css" />
<script src="{% static 'plugins/custom/datatables/datatables.bundle.js' %}"></script>
<script type="text/javascript">
  $(document).ready(function() {
    $('.instruments-list').DataTable({
      "pageLength": 25,
    });
  });
</script>

algo_trading/templates/instruments/list_instruments.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <section class="header">
      <h3>All instruments</h3>
      <p class="subtext help-text">List of all the instruments imported and their details</p>
    </section>

    <section class="instruments-display">
      {% include "instruments/display_meta_in_table.html" with instruments=instruments %}
    </section>
  </div>
{% endblock %}

algo_trading/templates/instruments/show.html
{% extends "base.html" %}

{% load static %}

{% block content %}
  <div class="container">
    <h2>Details for {{ instrument.get_instrument_type_display }}: {{ instrument.trading_symbol }}</h2>

    <p>
      <p>Symbol: {{ instrument.trading_symbol }}</p>
      <p>Name: {{ instrument.name }}</p>
      <p>Exchange: {{ instrument.exchange }}</p>
      <p>Instrument Type: {{ instrument.instrument_type }}</p>
      <p>Segment:{{ instrument.segment }}</p>
      <p>Expiry:{{ instrument.expiry }}</p>
      <p>Lot Size: {{ instrument.lot_size }}</p>
      <p>Tick Size: {{ instrument.tick_size }}</p>
      <p>Strike: {{ instrument.strike }}</p>
      <p>Exchange Token: {{ instrument.exchange_token }}</p>
      <p>Instrument Token: {{ instrument.instrument_token }}</p>
    </p>

    {% if daily_data.count > 0 %}
      <div class="table-responsive">
        <p class="ohlc-data-count">Total <strong>{{ daily_data.count }}</strong> OHLC values</p>
        <table class="ohlc-data table gy-5 gs-5 align-middle">
          <thead>
            <tr class="fw-bold text-muted bg-light">
              <th class="ps-4 rounded-start min-w-25px">Date</th>
              <th>Open</th>
              <th>High</th>
              <th>Low</th>
              <th class="rounded-end">Close</th>
            </tr>
          </thead>

          <tbody>
            {% for ohlc_row in daily_data.all %}
              <tr class="table-row ohlc-row">
                <td>{{ ohlc_row.date_in_tables }}</td>
                <td>{{ ohlc_row.open }}</td>
                <td>{{ ohlc_row.high }}</td>
                <td>{{ ohlc_row.low }}</td>
                <td>{{ ohlc_row.close }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    {% endif %}
  </div>
{% endblock %}

{% block scripts %}
  <link href="{% static 'plugins/custom/datatables/datatables.bundle.css' %}" rel="stylesheet" type="text/css" />
  <script src="{% static 'plugins/custom/datatables/datatables.bundle.js' %}"></script>
  <script type="text/javascript">
    $(document).ready(function() {
      $('.ohlc-data').DataTable({
        "pageLength": 25,
      });
    });
  </script>
{% endblock %}